kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: hub

kubeAPI:
  hostPort: "18043"

ports:
- port: 18080:80
  nodeFilters:
  - loadbalancer
- port: 18443:443
  nodeFilters:
  - loadbalancer
