kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: edge

servers: 1
agents: 2

kubeAPI:
  hostPort: "19043"

ports:
- port: 19080:80
  nodeFilters:
  - loadbalancer
- port: 19443:443
  nodeFilters:
  - loadbalancer
