apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application-manifestwork
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/satokitty/edge-playground.git
    path: clusters/hub/assets/managedCluster
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
